### ISSUE TITLE
Review Extracted Technical Metadata from CurationConcers/FITS

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/dams5-cc-pilot#23]
Please run the following file types through the CC ingest workflow so that technical metadata of each type may be reviewed by @ucsdlib/domm 
- [x] Audio
- [x] Video
- [x] Document (PDF, Word)
- [x] Image
- [x] Data (perhaps a few RDCP files?)

**Comment by lsitu** [comment]
@remerjohnson I've got the technical metadata exported for the format above. It looks like that the technical metadata extracted from CC is much more than what we want. These technical metadata include some of the fields from the characterization scheme but not all, which are specific to that format, and some fields are machine manage triples from fedora.
Attached are the examples in rdf+xml format. Could you take a look? Thanks. I think you can rename the following files to .xml for reviewing:
[cc-metadata-image.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542266/cc-metadata-image.txt)
[cc-metadata-video.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542264/cc-metadata-video.txt)
[cc-metadata-audio.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542265/cc-metadata-audio.txt)
[cc-metadata-word.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542267/cc-metadata-word.txt)
[cc-metadata-pdf.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542263/cc-metadata-pdf.txt)
[cc-metadata-data-txt.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542270/cc-metadata-data-txt.txt)
[cc-metadata-data-gzip.txt](https://github.com/ucsdlib/dams5-cc-pilot/files/542269/cc-metadata-data-gzip.txt)

**Comment by arwenhutt** [comment]
@lsitu These do look much richer than what we supported before, which is a great thing!  I think we'll want to include Stefan in this review, but he's OOO. 

So two clarifying questions, what feedback do you need on the CC/FITS extracted default metadata?  and what's the time frame on getting the feedback?

**Comment by lsitu** [comment]
@arwenhutt I think we just need to figure out whether the technical metadata extracted from CC/FITS is good for us. And I don't think we have any timeframe for the feedback. Thanks.

**Comment by remerjohnson** [comment]
@arwenhutt A big impetus for this issue was in [another issue](https://github.com/ucsdlib/dams5-cc-pilot/issues/18#issuecomment-249733335), because we wanted to see what exactly we would capture in `dams:format`. 

Now that we know there's a lot of metadata captured here, I don't know what (if anything) we need to use `dams:format` for? (size, extent, duration, MIME type, as is recommended in Dublin Core, is all covered in the extracted metadata).

**Comment by arwenhutt** [comment]
Thanks @remerjohnson that helps.  Agreed that the d4 property `dams:formatName` seems to map to `pre:hasFormatName` in FITS/CC model.

There is also the dc11:format, which is I think a different question that we'd need to consider.  As Ryan mentioned it's a fuzzy bucket that we don't really (I think) have a strong current use for, but we should consider how it relates to interoperability with others and mapping down to cc.

So if there are no other open questions, then we can always bring any other feedback from reviewing the outputs with Stefan up in a new ticket?

**Comment by remerjohnson** [comment]
@arwenhutt I _was_ referring to 1.1: [dc11:format](http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#format)

> The file format, physical medium, or dimensions of the resource.
> **Comment:** Examples of dimensions include size and duration. Recommended best practice is to use a controlled vocabulary such as the list of Internet Media Types [MIME].

**Comment by arwenhutt** [comment]
@remerjohnson have we used that before though?  I mean in both d4 and d5 format name is in other properties.

**Comment by remerjohnson** [comment]
@arwenhutt Right, for `dams:format` (line 88), I think we could probably get rid of the ucsd property, but then like you say, map dc11:format to some of the other properties within `ucsd:File` like formatName and formatVersion, although it could potentially map to many of the `ucsd:File` properties

What do you think, @mcritchlow?

**Comment by arwenhutt** [comment]
Weird, I don't see `dams:format` on line 88, just a grey text (inherited) `dc11:format`

**Comment by ghost** [comment]
I think dc:format on row 88 is describing the original physical object, at least that's how DPLA uses it.  That may be why it's greyed out - because we use the physicalDescription note.

**Comment by arwenhutt** [comment]
The grey indicates what (we think) we are inheriting from a previous tier of the model that we aren't modifying. `dc11:format` is coming from the base HydraWorks/CC install.  And we are proposing no modifications or changes to that.  

I agree with Greg that in this context, and interpreting it as other users (DPLA, UCSB) have, it's related to the original physical object.  Whether we want to use it for that or not is something that we can discuss.  But for now, it does not seem to affect the dev work since 1) we aren't asking for the creation of a new property or the modification of an existing CC property 2) we don't have a property in d4 that we are mapping to this field. 

@lsitu please let us know if there are any specific questions related to this that you still have.

**Comment by lsitu** [comment]
@arwenhutt I don't have any specific questions related to this but rather as what you've indicated, how to utilize these technical metadata extracted by CC. Thanks.

**Comment by mcritchlow** [comment]
Agreed that this extracted technical metadata (by default from CC) is our new baseline for technical metadata. Noted by @arwenhutt that we may revisit with @snabli to discuss supplemental file metadata
